Hide new comment form
GlotPress/gp-translation-helpers pull request #112
Opened 2022-09-13 21:31 UTC by trymebytes

#### Problem
It's sometimes confusing when you have multiple comment forms displayed at the same time. This is usually the case when a user clicks on the "Reply" button where a new comment form is displayed in addition to the comment form for new comments.

![Screenshot 2022-08-30 at 09-54-37 Visit %s’s website 2 translations](https://user-images.githubusercontent.com/203408/187381878-376e6c35-e822-4b50-9801-215513b4842d.png)

#### Solution

Hide the comment form for new comments
![toggle-comments](https://user-images.githubusercontent.com/203408/187382263-c7114c19-56ac-4bbd-910c-52ba6c4f29dc.gif)

2022-09-23 08:56 UTC, akirk approved these changes

2022-09-27 12:34 UTC, akirk commented
@amieiro mentioned that it would be good to make the summary text look like a button.

2022-09-28 09:02 UTC, akirk requested changes
Please make the "Start a new Conversation" a button

2022-09-29 15:27 UTC, amieiro commented
Currently, the button is full width:

![image](https://user-images.githubusercontent.com/1667814/193069631-08fbf7a1-3806-47f4-944a-82658e82907d.png)

I was thinking on a small button, like the reply buttons:

![image](https://user-images.githubusercontent.com/1667814/193072576-05678150-e0f1-483b-b907-9d27578b49f4.png)

With the same hover effect.

![image](https://user-images.githubusercontent.com/1667814/193073031-30e5a1b1-ab4b-450f-8347-b0317b80ded8.png)

What do you think about this? We have to add the same CSS at translate.w.org. I am going to push this commit, and if you don't like it, please, revert it.

2022-09-30 07:36 UTC, amieiro commented
It works fine at https://translate.wordpress.org

![image](https://user-images.githubusercontent.com/1667814/193216659-0734a9fb-f58a-4508-865a-c35cfd2f7041.png)

Opened element:

![image](https://user-images.githubusercontent.com/1667814/193216841-87027dc4-7cbc-4ce9-b5fa-1df2986b4d2a.png)

2022-09-30 11:11 UTC, amieiro approved these changes

2022-09-30 14:13 UTC, merged