WIP - Link back to translation
GlotPress/gp-translation-helpers pull request #13
Opened 2022-01-27 20:07 UTC by trymebytes

2022-01-28 12:22 UTC, akirk requested changes
Looks good at first glance but could you rebase before I do a full review? Currently this PR has a merge conflict.

2022-01-28 15:07 UTC, trymebytes commented
> Looks good at first glance but could you rebase before I do a full review? Currently this PR has a merge conflict.

Done!

2022-02-14 14:58 UTC, akirk requested changes
There is something not quite right for waiting translations:
```
Waiting translation:
Notice: Undefined variable: translation_permalink in /Users/alex/Sites/localhost/wp/wp-content/plugins/gp-translation-tools/templates/original-permalink.php on line 88
```

Here is a waiting translation for me: https://glotpress.local/projects/wp/dev/2439646/zh-tw/default/

2022-02-14 15:11 UTC, akirk commented on templates/original-permalink.php
>  					   ( '' == $e->translation_5 ) ) :
Would that work?
```suggestion
					   ( '' == $e->translation_5 ) ) :
					   $translation_permalink = GP_Route_Translation_Helpers::get_translation_permalink(
			$project,
			$locale_slug,
			$translation_set_slug,
			$original_id,
			$e->id
		);
```

2022-02-25 09:15 UTC, akirk commented
I've added two things:

### Status background
Before:
![Screenshot 2022-02-25 at 09 58 52](https://user-images.githubusercontent.com/203408/155686300-baa5a24e-de51-4d2e-a78d-da01a3f13d08.png)
After:
![Screenshot 2022-02-25 at 10 14 34](https://user-images.githubusercontent.com/203408/155688427-c9366a1c-ee5a-451e-a682-3336a15cb1c1.png)

### Other locale links
Before:
![Screenshot 2022-02-25 at 09 58 55](https://user-images.githubusercontent.com/203408/155688486-b663f7a3-5df6-4e8b-8684-9c1df239bc6f.png)

After:
![Screenshot 2022-02-25 at 09 58 34](https://user-images.githubusercontent.com/203408/155688515-d1faef95-2138-48eb-bb79-424963981d60.png)

2022-02-25 09:16 UTC, akirk approved these changes
Ready to merge from me, @trymebytes could you also test my changes? Thanks!

2022-02-25 10:20 UTC, trymebytes commented
> Ready to merge from me, @trymebytes could you also test my changes? Thanks!

Looks good to me! I'll go ahead and merge, thanks!

2022-02-25 10:21 UTC, merged